### ISSUE TITLE
Timeout Error when checking for pending transactions on mainnet.

### ISSUE THREAD

**Issue by lullis** [mushroomlabs/hub20#48]
When running on mainnet, the command track_pending_payments is failing occasionally with Timeout Errors.

```
job_track_payments_1   | Traceback (most recent call last):
job_track_payments_1   |   File "/usr/local/bin/django-admin", line 10, in <module>
job_track_payments_1   |     sys.exit(execute_from_command_line())
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
job_track_payments_1   |     utility.execute()
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
job_track_payments_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
job_track_payments_1   |     self.execute(*args, **cmd_options)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
job_track_payments_1   |     output = self.handle(*args, **options)
job_track_payments_1   |   File "/app/hub20/apps/core/management/commands/track_pending_payments.py", line 98, in handle
job_track_payments_1   |     loop.run_until_complete(track_pending_transactions(w3))
job_track_payments_1   |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
job_track_payments_1   |     return future.result()
job_track_payments_1   |   File "/app/hub20/apps/core/management/commands/track_pending_payments.py", line 33, in track_pending_transactions
job_track_payments_1   |     get_mined_transaction_data(w3, tx) for tx in tx_filter.get_new_entries()
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/_utils/filters.py", line 159, in get_new_entries
job_track_payments_1   |     log_entries = self._filter_valid_entries(self.web3.eth.getFilterChanges(self.filter_id))
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 487, in getFilterChanges
job_track_payments_1   |     RPC.eth_getFilterChanges, [filter_id],
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
job_track_payments_1   |     response = self._make_request(method, params)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
job_track_payments_1   |     return request_func(method, params)
job_track_payments_1   |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
job_track_payments_1   |     return make_request(method, params)
job_track_payments_1   |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
job_track_payments_1   |     result = make_request(method, params)
job_track_payments_1   |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
job_track_payments_1   |     response = make_request(method, params)
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/providers/websocket.py", line 137, in make_request
job_track_payments_1   |     return future.result()
job_track_payments_1   |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 432, in result
job_track_payments_1   |     return self.__get_result()
job_track_payments_1   |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
job_track_payments_1   |     raise self._exception
job_track_payments_1   |   File "/usr/local/lib/python3.7/site-packages/web3/providers/websocket.py", line 125, in coro_make_request
job_track_payments_1   |     timeout=self.websocket_timeout
job_track_payments_1   |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
job_track_payments_1   |     raise futures.TimeoutError()
job_track_payments_1   | concurrent.futures._base.TimeoutError
```

**Comment by lullis** [comment]
Issue fixed and further improvements made: only one web3 client is initalized per-process, reducing the number of websockets opened (one per-process instead of background task)
